### ISSUE TITLE
Doesn't work with Kicad 6 or Nightly

### ISSUE THREAD

**Issue by AiGreek** [arjhun/KiCad-helper-scripts#5]
```
Application: Editeur de Schématique KiCad (64-bit)

Version: (6.0.0-rc1-306-g01eebd0b9d), release build

Libraries:
	wxWidgets 3.1.5
	libcurl/7.78.0-DEV Schannel zlib/1.2.11

Platform: Windows 10 (build 19043), 64-bit edition, 64 bit, Little endian, wxMSW

Build Info:
	Date: Dec  3 2021 00:00:11
	wxWidgets: 3.1.5 (wchar_t,wx containers)
	Boost: 1.76.0
	OCC: 7.5.0
	Curl: 7.78.0-DEV
	ngspice: 35
	Compiler: Visual C++ 1929 without C++ ABI

Build settings:
	KICAD_USE_OCC=ON
	KICAD_SPICE=ON
```

Tried this script with the "last" Kicad version and have this error :
`Not a KiCad EEschema file! exiting!`

**Comment by arjhun** [comment]
Hi this error is valid because this script is written for EESCHEMA V2. I wrote this for versions using this file format. I have not yet looked into KICAD v6. I found this link:
https://gitlab.com/kicad/code/kicad/-/wikis/KiCad-6.0-Roadmap#s-expression-file-format
They are now using a new file format. I think the next step in the development of my tool would be an interface plugin and not something that manipulates a schema file directly... If you want to pick this up you can fork this library. Thanks for your message!
